import os

path = r'c:\Users\Ayushman\Desktop\circuit_pulse\engine\circuit.py'
with open(path, 'r') as f:
    lines = f.readlines()

new_lines = []
for line in lines:
    if 'all_errors = critical_errors + errors' in line:
        new_lines.append('        # --- NEW TOPOLOGY GRAPH SOLVER ---\n')
        new_lines.append('        nodes = []\n')
        new_lines.append('        for i, b in enumerate(smoothed_boxes):\n')
        new_lines.append('            nodes.append({"id": i, "class": b["class"], "box": b["bbox"]})\n')
        new_lines.append('        \n')
        new_lines.append('        has_mcu = any(n["class"] in ["esp32", "arduino_uno", "arduino_nano", "arduino_mega"] for n in nodes)\n')
        new_lines.append('        \n')
        new_lines.append('        if len(nodes) > 2 and not wire_boxes:\n')
        new_lines.append('            errors.append({\n')
        new_lines.append('                "id": "err_topology_open",\n')
        new_lines.append('                "type": "open_circuit",\n')
        new_lines.append('                "severity": "critical",\n')
        new_lines.append('                "message": "Topology Error: Circuit is completely open",\n')
        new_lines.append('                "remedy": "Connect components to the Microcontroller using Jumper Wires",\n')
        new_lines.append('                "tts": "Circuit is open. Connect components to the Microcontroller using Jumper Wires"\n')
        new_lines.append('            })\n')
        new_lines.append('            \n')
        new_lines.append('        components_to_connect = [n for n in nodes if n["class"] not in ["esp32", "arduino_uno", "arduino_nano", "arduino_mega", "breadboard", "wire"]]\n')
        new_lines.append('        \n')
        new_lines.append('        for comp in components_to_connect:\n')
        new_lines.append('            c_box = comp["box"]\n')
        new_lines.append('            c_name = comp["class"].replace("_", " ").upper()\n')
        new_lines.append('            \n')
        new_lines.append('            touches_bb = any(self._check_overlap(c_box, b["bbox"]) for b in breadboard_boxes)\n')
        new_lines.append('            if not touches_bb:\n')
        new_lines.append('                loc = self._describe_location(c_box, fw, fh)\n')
        new_lines.append('                errors.append({\n')
        new_lines.append('                    "id": f"err_not_on_bb_{comp[\'id\']}",\n')
        new_lines.append('                    "type": "placement_error",\n')
        new_lines.append('                    "severity": "error",\n')
        new_lines.append('                    "message": f"{c_name} at {loc} is not placed on the Breadboard",\n')
        new_lines.append('                    "remedy": f"Move the {c_name} so its pins are firmly inserted into the Breadboard holes",\n')
        new_lines.append('                    "tts": f"{c_name} is not on the Breadboard. Please insert it into the breadboard holes."\n')
        new_lines.append('                })\n')
        new_lines.append('                continue\n')
        new_lines.append('                \n')
        new_lines.append('            touches_wire = any(self._check_overlap(c_box, w["bbox"]) for w in wire_boxes)\n')
        new_lines.append('            if not touches_wire:\n')
        new_lines.append('                loc = self._describe_location(c_box, fw, fh)\n')
        new_lines.append('                errors.append({\n')
        new_lines.append('                    "id": f"err_no_wire_{comp[\'id\']}",\n')
        new_lines.append('                    "type": "wiring_error",\n')
        new_lines.append('                    "severity": "error",\n')
        new_lines.append('                    "message": f"{c_name} at {loc} has no wire connection",\n')
        new_lines.append('                    "remedy": f"Connect a jumper wire from the {c_name} row to the Microcontroller",\n')
        new_lines.append('                    "tts": f"{c_name} has no wire. Connect a jumper wire from it to the microcontroller."\n')
        new_lines.append('                })\n')
        new_lines.append('                \n')
    new_lines.append(line)

with open(path, 'w') as f:
    f.writelines(new_lines)
